# Generated by Django 2.0.3 on 2018-03-16 12:50

from django.db import migrations, models
import linkler.models


class Migration(migrations.Migration):

    dependencies = [
        ('linkler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to=linkler.models.link.save_path),
        ),
    ]
